### ISSUE TITLE
Incorrect Array Resizing during testing

### ISSUE THREAD

**Issue by Sourish97** [shashikg/EmotionRecognition#1]
Tried the same code but for 5 classes and got a similar error during 7 classes too after retraining. I'm attaching the FER excel file too just for reference. Everything is working for the models that you provided in the repository but after retraining on the dataset that is now available on the Kaggle website it's giving an error
[emotion_recognizer.pdf](https://github.com/shashikg/EmotionRecognition/files/2873044/emotion_recognizer.pdf)
[plot_confusion_matrix.pdf](https://github.com/shashikg/EmotionRecognition/files/2873045/plot_confusion_matrix.pdf)

FER dataset
https://drive.google.com/file/d/11w8veZ71XYzKw8dkdrLI4fyqj0sb8OAj/view?usp=sharing

**Comment by shashikg** [comment]
@Sourish97 please upload the exported pdf for "emotion_trainer.ipynb" as in that only I can look at the model which is being trained.

**Comment by Sourish97** [comment]
Here's the required file along with that persistent error
[emotion_trainer.pdf](https://github.com/shashikg/EmotionRecognition/files/2873139/emotion_trainer.pdf)
<img width="689" alt="error" src="https://user-images.githubusercontent.com/23509230/52915734-8621fd80-32fd-11e9-8ea7-6bf1e9482221.PNG">

**Comment by shashikg** [comment]
@Sourish97 
thanks a lot for reporting the issue there was one minor bug in the following line in **emotion_trainer.ipynb**:
`m.save('saved_model/ensemble.h5')`

in place of that it should be:
`modele.save('saved_model/ensemble.h5')`
